"""empty message

Revision ID: 6f4538d6e4df
Revises: 122e6988f823
Create Date: 2021-11-06 19:06:55.481787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f4538d6e4df'
down_revision = '122e6988f823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('book_author', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'book_author')
    # ### end Alembic commands ###
