"""empty message

Revision ID: d138ddde2390
Revises: 6f4538d6e4df
Create Date: 2021-11-06 19:56:26.926371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd138ddde2390'
down_revision = '6f4538d6e4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_user_id_fkey', 'books', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
