"""empty message

Revision ID: e0346fe40c06
Revises: a2624ea4d718
Create Date: 2021-11-07 15:43:16.153867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0346fe40c06'
down_revision = 'a2624ea4d718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'owner')
    # ### end Alembic commands ###
